- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.3915325860456083
  final_capital: 1072867.879415053
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.6465635723009013
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 72867.8794150529
  sharpe_ratio: 0.18662829609043358
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.3915325860456083
  final_capital: 1072867.879415053
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.6465635723009013
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 72867.8794150529
  sharpe_ratio: 0.18662829609043358
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.3915325860456083
  final_capital: 1072867.879415053
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.6465635723009013
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 72867.8794150529
  sharpe_ratio: 0.18662829609043358
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.3915325860456083
  final_capital: 1072867.879415053
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.6465635723009013
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 72867.8794150529
  sharpe_ratio: 0.18662829609043358
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.3915325860456083
  final_capital: 1072867.879415053
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.6465635723009013
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 72867.8794150529
  sharpe_ratio: 0.18662829609043358
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.3915325860456083
  final_capital: 1072867.879415053
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.6465635723009013
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 72867.8794150529
  sharpe_ratio: 0.18662829609043358
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.3915325860456083
  final_capital: 1072867.879415053
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.6465635723009013
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 72867.8794150529
  sharpe_ratio: 0.18662829609043358
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.3915325860456083
  final_capital: 1072867.879415053
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.6465635723009013
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 72867.8794150529
  sharpe_ratio: 0.18662829609043358
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.3915325860456083
  final_capital: 1072867.879415053
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.6465635723009013
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 72867.8794150529
  sharpe_ratio: 0.18662829609043358
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.3915325860456083
  final_capital: 1072867.879415053
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.6465635723009013
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 72867.8794150529
  sharpe_ratio: 0.18662829609043358
  total_trades: 5
  win_rate: 60.0
