- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 5.7762595121968685
  final_capital: 11818.990059219539
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.888818538806542
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1818.9900592195397
  sharpe_ratio: 0.1866282960904336
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 5.7762595121968685
  final_capital: 11818.990059219539
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.888818538806542
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1818.9900592195397
  sharpe_ratio: 0.1866282960904336
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 5.7762595121968685
  final_capital: 11818.990059219539
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.888818538806542
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1818.9900592195397
  sharpe_ratio: 0.1866282960904336
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 5.7762595121968685
  final_capital: 11818.990059219539
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.888818538806542
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1818.9900592195397
  sharpe_ratio: 0.1866282960904336
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 5.7762595121968685
  final_capital: 11818.990059219539
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.888818538806542
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1818.9900592195397
  sharpe_ratio: 0.1866282960904336
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 5.7762595121968685
  final_capital: 11818.990059219539
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.888818538806542
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1818.9900592195397
  sharpe_ratio: 0.1866282960904336
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 5.7762595121968685
  final_capital: 11818.990059219539
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.888818538806542
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1818.9900592195397
  sharpe_ratio: 0.1866282960904336
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 5.7762595121968685
  final_capital: 11818.990059219539
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.888818538806542
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1818.9900592195397
  sharpe_ratio: 0.1866282960904336
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 5.7762595121968685
  final_capital: 11818.990059219539
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.888818538806542
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1818.9900592195397
  sharpe_ratio: 0.1866282960904336
  total_trades: 5
  win_rate: 60.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 5.7762595121968685
  final_capital: 11818.990059219539
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.888818538806542
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1818.9900592195397
  sharpe_ratio: 0.1866282960904336
  total_trades: 5
  win_rate: 60.0
