- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 17.991012267558972
  final_capital: 1016681.4337393643
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.0
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 20
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 16681.43373936423
  sharpe_ratio: 4.349097276072974
  total_trades: 1
  win_rate: 100.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 17.991012267558972
  final_capital: 1016681.4337393643
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.0
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 20
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 16681.43373936423
  sharpe_ratio: 4.349097276072974
  total_trades: 1
  win_rate: 100.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 17.991012267558972
  final_capital: 1016681.4337393643
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.0
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 20
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 16681.43373936423
  sharpe_ratio: 4.349097276072974
  total_trades: 1
  win_rate: 100.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 17.991012267558972
  final_capital: 1016681.4337393643
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.0
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 20
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 16681.43373936423
  sharpe_ratio: 4.349097276072974
  total_trades: 1
  win_rate: 100.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 17.991012267558972
  final_capital: 1016681.4337393643
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.0
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 20
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 16681.43373936423
  sharpe_ratio: 4.349097276072974
  total_trades: 1
  win_rate: 100.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 17.991012267558972
  final_capital: 1016681.4337393643
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.0
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 20
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 16681.43373936423
  sharpe_ratio: 4.349097276072974
  total_trades: 1
  win_rate: 100.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 17.991012267558972
  final_capital: 1016681.4337393643
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.0
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 20
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 16681.43373936423
  sharpe_ratio: 4.349097276072974
  total_trades: 1
  win_rate: 100.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 17.991012267558972
  final_capital: 1016681.4337393643
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.0
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 20
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 16681.43373936423
  sharpe_ratio: 4.349097276072974
  total_trades: 1
  win_rate: 100.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 17.991012267558972
  final_capital: 1016681.4337393643
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.0
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 1.8
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 20
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 16681.43373936423
  sharpe_ratio: 4.349097276072974
  total_trades: 1
  win_rate: 100.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 17.991012267558972
  final_capital: 1016681.4337393643
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.0
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 20
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 16681.43373936423
  sharpe_ratio: 4.349097276072974
  total_trades: 1
  win_rate: 100.0
