- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.0942392524698317
  final_capital: 10863.147123841885
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.1105779076099602
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 30
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 863.1471238418853
  sharpe_ratio: -0.21855045196782552
  total_trades: 8
  win_rate: 62.5
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.0942392524698317
  final_capital: 10863.147123841885
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.1105779076099602
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 70
      oversold: 30
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 863.1471238418853
  sharpe_ratio: -0.21855045196782552
  total_trades: 8
  win_rate: 62.5
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.0942392524698317
  final_capital: 10863.147123841885
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.1105779076099602
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 75
      oversold: 30
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 863.1471238418853
  sharpe_ratio: -0.21855045196782552
  total_trades: 8
  win_rate: 62.5
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.4341932818942045
  final_capital: 11318.753283633743
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.65740720648333
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 2.0
    rsi:
      length: 20
      overbought: 65
      oversold: 30
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1318.7532836337436
  sharpe_ratio: -0.2198300553473864
  total_trades: 10
  win_rate: 80.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.4341932818942045
  final_capital: 11318.753283633743
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.65740720648333
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 2.0
    rsi:
      length: 20
      overbought: 70
      oversold: 30
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1318.7532836337436
  sharpe_ratio: -0.2198300553473864
  total_trades: 10
  win_rate: 80.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.4341932818942045
  final_capital: 11318.753283633743
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.65740720648333
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 2.0
    rsi:
      length: 20
      overbought: 75
      oversold: 30
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1318.7532836337436
  sharpe_ratio: -0.2198300553473864
  total_trades: 10
  win_rate: 80.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.4341932818942045
  final_capital: 11318.753283633743
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.65740720648333
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 2.0
    rsi:
      length: 20
      overbought: 65
      oversold: 30
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1318.7532836337436
  sharpe_ratio: -0.2198300553473864
  total_trades: 10
  win_rate: 80.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.4341932818942045
  final_capital: 11318.753283633743
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.65740720648333
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 2.0
    rsi:
      length: 20
      overbought: 70
      oversold: 30
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1318.7532836337436
  sharpe_ratio: -0.2198300553473864
  total_trades: 10
  win_rate: 80.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.4341932818942045
  final_capital: 11318.753283633743
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.65740720648333
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 2.0
    rsi:
      length: 20
      overbought: 75
      oversold: 30
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1318.7532836337436
  sharpe_ratio: -0.2198300553473864
  total_trades: 10
  win_rate: 80.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.0762417016000123
  final_capital: 10855.499645240805
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.111483851686438
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 20
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 855.4996452408054
  sharpe_ratio: -0.22072632215633875
  total_trades: 8
  win_rate: 62.5
