# Trading configuration for Nifty 100 stocks
asset_filters:
  exchange: NSE
  exclude_symbols:
  - -BE
  - -BZ
  - -SM
  - -SG
  - GB
  - SDL
  instrument_type: EQ
  segment: NSE
interval: day
months_of_history: 60
stocks:
  - symbol: ADANIENT
    config: config/stock_configs/ADANIENT.yaml
  - symbol: ADANIPORTS
    config: config/stock_configs/ADANIPORTS.yaml
  - symbol: APOLLOHOSP
    config: config/stock_configs/APOLLOHOSP.yaml
  - symbol: ASIANPAINT
    config: config/stock_configs/ASIANPAINT.yaml
  - symbol: AXISBANK
    config: config/stock_configs/AXISBANK.yaml
  - symbol: BAJAJ-AUTO
    config: config/stock_configs/BAJAJ-AUTO.yaml
  - symbol: BAJFINANCE
    config: config/stock_configs/BAJFINANCE.yaml
  - symbol: BAJAJFINSV
    config: config/stock_configs/BAJAJFINSV.yaml
  - symbol: BPCL
    config: config/stock_configs/BPCL.yaml
  - symbol: BHARTIARTL
    config: config/stock_configs/BHARTIARTL.yaml
  - symbol: BRITANNIA
    config: config/stock_configs/BRITANNIA.yaml
  - symbol: CIPLA
    config: config/stock_configs/CIPLA.yaml
  - symbol: COALINDIA
    config: config/stock_configs/COALINDIA.yaml
  - symbol: DIVISLAB
    config: config/stock_configs/DIVISLAB.yaml
  - symbol: DRREDDY
    config: config/stock_configs/DRREDDY.yaml
  - symbol: EICHERMOT
    config: config/stock_configs/EICHERMOT.yaml
  - symbol: GRASIM
    config: config/stock_configs/GRASIM.yaml
  - symbol: HCLTECH
    config: config/stock_configs/HCLTECH.yaml
  - symbol: HDFCBANK
    config: config/stock_configs/HDFCBANK.yaml
  - symbol: HDFCLIFE
    config: config/stock_configs/HDFCLIFE.yaml
  - symbol: HEROMOTOCO
    config: config/stock_configs/HEROMOTOCO.yaml
  - symbol: HINDALCO
    config: config/stock_configs/HINDALCO.yaml
  - symbol: HINDUNILVR
    config: config/stock_configs/HINDUNILVR.yaml
  - symbol: ICICIBANK
    config: config/stock_configs/ICICIBANK.yaml
  - symbol: INDUSINDBK
    config: config/stock_configs/INDUSINDBK.yaml
  - symbol: INFY
    config: config/stock_configs/INFY.yaml
  - symbol: ITC
    config: config/stock_configs/ITC.yaml
  - symbol: JSWSTEEL
    config: config/stock_configs/JSWSTEEL.yaml
  - symbol: KOTAKBANK
    config: config/stock_configs/KOTAKBANK.yaml
  - symbol: LT
    config: config/stock_configs/LT.yaml
  - symbol: M&M
    config: config/stock_configs/M&M.yaml
  - symbol: MARUTI
    config: config/stock_configs/MARUTI.yaml
  - symbol: NESTLEIND
    config: config/stock_configs/NESTLEIND.yaml
  - symbol: NTPC
    config: config/stock_configs/NTPC.yaml
  - symbol: ONGC
    config: config/stock_configs/ONGC.yaml
  - symbol: POWERGRID
    config: config/stock_configs/POWERGRID.yaml
  - symbol: RELIANCE
    config: config/stock_configs/RELIANCE.yaml
  - symbol: SBILIFE
    config: config/stock_configs/SBILIFE.yaml
  - symbol: SBIN
    config: config/stock_configs/SBIN.yaml
  - symbol: SUNPHARMA
    config: config/stock_configs/SUNPHARMA.yaml
  - symbol: TCS
    config: config/stock_configs/TCS.yaml
  - symbol: TATACONSUM
    config: config/stock_configs/TATACONSUM.yaml
  - symbol: TATAMOTORS
    config: config/stock_configs/TATAMOTORS.yaml
  - symbol: TATASTEEL
    config: config/stock_configs/TATASTEEL.yaml
  - symbol: TECHM
    config: config/stock_configs/TECHM.yaml
  - symbol: TITAN
    config: config/stock_configs/TITAN.yaml
  - symbol: ULTRACEMCO
    config: config/stock_configs/ULTRACEMCO.yaml
  - symbol: UPL
    config: config/stock_configs/UPL.yaml
  - symbol: WIPRO
    config: config/stock_configs/WIPRO.yaml
  - symbol: BHEL
    config: config/stock_configs/BHEL.yaml
  - symbol: NMDC
    config: config/stock_configs/NMDC.yaml
  - symbol: BANKBARODA
    config: config/stock_configs/BANKBARODA.yaml
  - symbol: CANBK
    config: config/stock_configs/CANBK.yaml
  - symbol: PNB
    config: config/stock_configs/PNB.yaml
  - symbol: IDFC
    config: config/stock_configs/IDFC.yaml
  - symbol: BIOCON
    config: config/stock_configs/BIOCON.yaml
  - symbol: SAIL
    config: config/stock_configs/SAIL.yaml
  - symbol: PFC
    config: config/stock_configs/PFC.yaml
  - symbol: RECLTD
    config: config/stock_configs/RECLTD.yaml
  - symbol: GAIL
    config: config/stock_configs/GAIL.yaml
  - symbol: JINDALSTEL
    config: config/stock_configs/JINDALSTEL.yaml
  - symbol: VEDL
    config: config/stock_configs/VEDL.yaml
  - symbol: IDFCFIRSTB
    config: config/stock_configs/IDFCFIRSTB.yaml
  - symbol: HAVELLS
    config: config/stock_configs/HAVELLS.yaml
  - symbol: GODREJCP
    config: config/stock_configs/GODREJCP.yaml
  - symbol: MARICO
    config: config/stock_configs/MARICO.yaml
  - symbol: DABUR
    config: config/stock_configs/DABUR.yaml
  - symbol: ICICIGI
    config: config/stock_configs/ICICIGI.yaml
  - symbol: HDFCAMC
    config: config/stock_configs/HDFCAMC.yaml
  - symbol: NAUKRI
    config: config/stock_configs/NAUKRI.yaml
  - symbol: ADANIGREEN
    config: config/stock_configs/ADANIGREEN.yaml
  - symbol: PAGEIND
    config: config/stock_configs/PAGEIND.yaml
  - symbol: PIDILITIND
    config: config/stock_configs/PIDILITIND.yaml
  - symbol: LUPIN
    config: config/stock_configs/LUPIN.yaml
  - symbol: SIEMENS
    config: config/stock_configs/SIEMENS.yaml
  - symbol: DLF
    config: config/stock_configs/DLF.yaml
  - symbol: SRTRANSFIN
    config: config/stock_configs/SRTRANSFIN.yaml
  - symbol: INDUSTOWER
    config: config/stock_configs/INDUSTOWER.yaml
  - symbol: INDIGO
    config: config/stock_configs/INDIGO.yaml
  - symbol: COLPAL
    config: config/stock_configs/COLPAL.yaml
  - symbol: GODREJPROP
    config: config/stock_configs/GODREJPROP.yaml
  - symbol: CHOLAFIN
    config: config/stock_configs/CHOLAFIN.yaml
  - symbol: BOSCHLTD
    config: config/stock_configs/BOSCHLTD.yaml
  - symbol: PIIND
    config: config/stock_configs/PIIND.yaml
  - symbol: BERGEPAINT
    config: config/stock_configs/BERGEPAINT.yaml
  - symbol: SRF
    config: config/stock_configs/SRF.yaml
  - symbol: TVSMOTOR
    config: config/stock_configs/TVSMOTOR.yaml
  - symbol: TRENT
    config: config/stock_configs/TRENT.yaml
  - symbol: MPHASIS
    config: config/stock_configs/MPHASIS.yaml
  - symbol: MUTHOOTFIN
    config: config/stock_configs/MUTHOOTFIN.yaml
  - symbol: ZYDUSLIFE
    config: config/stock_configs/ZYDUSLIFE.yaml
  - symbol: GLAND
    config: config/stock_configs/GLAND.yaml
  - symbol: ZOMATO
    config: config/stock_configs/ZOMATO.yaml
  - symbol: APOLLOTYRE
    config: config/stock_configs/APOLLOTYRE.yaml
  - symbol: L&TFH
    config: config/stock_configs/L&TFH.yaml
  - symbol: BEL
    config: config/stock_configs/BEL.yaml
  - symbol: HONAUT
    config: config/stock_configs/HONAUT.yaml
  - symbol: AARTIIND
    config: config/stock_configs/AARTIIND.yaml
  - symbol: LICI
    config: config/stock_configs/LICI.yaml
  - symbol: LTIM
    config: config/stock_configs/LTIM.yaml
  - symbol: ABBOTINDIA
    config: config/stock_configs/ABBOTINDIA.yaml
  - symbol: ABCAPITAL
    config: config/stock_configs/ABCAPITAL.yaml 