- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.6304320182926064
  final_capital: 1160434.2992606894
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 7.227594617409299
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 160434.29926068947
  sharpe_ratio: 0.250441278102663
  total_trades: 10
  win_rate: 80.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.6304320182926064
  final_capital: 1160434.2992606894
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 7.227594617409299
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 160434.29926068947
  sharpe_ratio: 0.250441278102663
  total_trades: 10
  win_rate: 80.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.6304320182926064
  final_capital: 1160434.2992606894
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 7.227594617409299
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 160434.29926068947
  sharpe_ratio: 0.250441278102663
  total_trades: 10
  win_rate: 80.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.6304320182926064
  final_capital: 1160434.2992606894
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 7.227594617409299
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 160434.29926068947
  sharpe_ratio: 0.250441278102663
  total_trades: 10
  win_rate: 80.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.6304320182926064
  final_capital: 1160434.2992606894
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 7.227594617409299
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 160434.29926068947
  sharpe_ratio: 0.250441278102663
  total_trades: 10
  win_rate: 80.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.6304320182926064
  final_capital: 1160434.2992606894
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 7.227594617409299
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 160434.29926068947
  sharpe_ratio: 0.250441278102663
  total_trades: 10
  win_rate: 80.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.5631086349526386
  final_capital: 1157292.00853731
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 7.341358845665851
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 157292.00853731
  sharpe_ratio: 0.16878551030169447
  total_trades: 12
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.5631086349526386
  final_capital: 1157292.00853731
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 7.341358845665851
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 157292.00853731
  sharpe_ratio: 0.16878551030169447
  total_trades: 12
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.5631086349526386
  final_capital: 1157292.00853731
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 7.341358845665851
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 157292.00853731
  sharpe_ratio: 0.16878551030169447
  total_trades: 12
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.817263648091539
  final_capital: 1122569.484082124
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 7.360399095098289
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 2.5
    rsi:
      length: 10
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 122569.48408212407
  sharpe_ratio: 0.14249471164626276
  total_trades: 10
  win_rate: 80.0
