atr:
  window: 14
bollinger_bands:
  length: 20
  std: 2.0
columns:
  close: close
  high: high
  low: low
  open: open
  timestamp: timestamp
  volume: volume
ema:
  period: 20
macd:
  fast_period: 12
  signal_period: 9
  slow_period: 26
performance:
  cagr: 2.956476105385697
  final_capital: 1129268.57086603
  max_drawdown: 5.175527901643822
  realized_pnl: 129268.57086602986
  sharpe_ratio: 0.21434611300534265
  total_trades: 11
  win_rate: 72.72727272727273
risk_management:
  stop_loss_atr_multiplier: 2.0
  take_profit_atr_multiplier: 3.0
rsi:
  length: 14
  overbought: 70
  oversold: 30
support_resistance:
  resistance_period: 20
  support_period: 20
