atr:
  window: 14
bollinger_bands:
  num_std_dev: 2.0
  window: 20
columns:
  close: close
  high: high
  low: low
  open: open
  timestamp: timestamp
  volume: volume
ema:
  period: 21
macd:
  fast_period: 8
  signal_period: 6
  slow_period: 18
metadata:
  optimization_timestamp: '2025-03-17 08:18:36'
  training_period:
    end_date: '2024-09-13'
    start_date: '2020-05-19'
risk_management:
  stop_loss_atr_multiplier: 2.0
  take_profit_atr_multiplier: 3.0
rsi:
  overbought: 75
  oversold: 30
  window: 10
support_resistance:
  resistance_period: 21
  support_period: 10
