atr:
  window: 14
bollinger_bands:
  length: 20
  std: 2.0
columns:
  close: close
  high: high
  low: low
  open: open
  timestamp: timestamp
  volume: volume
ema:
  period: 20
macd:
  fast_period: 12
  signal_period: 9
  slow_period: 26
performance:
  cagr: 1.014202248187468
  final_capital: 1038431.6135730733
  max_drawdown: 0.7263985514588143
  realized_pnl: 38431.61357307329
  sharpe_ratio: -0.17255361639279074
  total_trades: 9
  win_rate: 55.55555555555556
risk_management:
  stop_loss_atr_multiplier: 2.0
  take_profit_atr_multiplier: 3.0
rsi:
  length: 14
  overbought: 70
  oversold: 30
support_resistance:
  resistance_period: 20
  support_period: 20
