atr:
  window: 14
bollinger_bands:
  num_std_dev: 2.5
  window: 14
columns:
  close: close
  high: high
  low: low
  open: open
  timestamp: timestamp
  volume: volume
ema:
  period: 21
macd:
  fast_period: 12
  signal_period: 6
  slow_period: 24
metadata:
  optimization_timestamp: '2025-03-17 08:31:48'
  training_period:
    end_date: '2024-09-13'
    start_date: '2020-05-19'
risk_management:
  stop_loss_atr_multiplier: 2.0
  take_profit_atr_multiplier: 3.0
rsi:
  overbought: 70
  oversold: 35
  window: 21
support_resistance:
  resistance_period: 14
  support_period: 21
