atr:
  window: 14
bollinger_bands:
  length: 20
  std: 2.0
columns:
  close: close
  high: high
  low: low
  open: open
  timestamp: timestamp
  volume: volume
ema:
  period: 20
macd:
  fast_period: 12
  signal_period: 9
  slow_period: 26
performance:
  cagr: 2.0756518051155526
  final_capital: 1090911.2395881533
  max_drawdown: 2.3243955769192506
  realized_pnl: 90911.23958815339
  sharpe_ratio: 0.03023660841909492
  total_trades: 14
  win_rate: 71.42857142857143
risk_management:
  stop_loss_atr_multiplier: 2.0
  take_profit_atr_multiplier: 3.0
rsi:
  length: 14
  overbought: 70
  oversold: 30
support_resistance:
  resistance_period: 20
  support_period: 20
