atr:
  window: 14
bollinger_bands:
  length: 20
  std: 2.0
columns:
  close: close
  high: high
  low: low
  open: open
  timestamp: timestamp
  volume: volume
ema:
  period: 20
macd:
  fast_period: 12
  signal_period: 9
  slow_period: 26
performance:
  cagr: 0.43052395524423304
  final_capital: 1017787.285140135
  max_drawdown: 2.2873023570044357
  realized_pnl: 17787.285140135005
  sharpe_ratio: -0.5462949042798122
  total_trades: 19
  win_rate: 52.63157894736842
risk_management:
  stop_loss_atr_multiplier: 2.0
  take_profit_atr_multiplier: 3.0
rsi:
  length: 14
  overbought: 70
  oversold: 30
support_resistance:
  resistance_period: 20
  support_period: 20
