atr:
  window: 14
bollinger_bands:
  length: 20
  std: 2.0
columns:
  close: close
  high: high
  low: low
  open: open
  timestamp: timestamp
  volume: volume
ema:
  period: 20
macd:
  fast_period: 12
  signal_period: 9
  slow_period: 26
performance:
  cagr: 1.0657711004286474
  final_capital: 1048112.7796991849
  max_drawdown: 5.677536759121577
  realized_pnl: 48112.77969918489
  sharpe_ratio: -0.3620468918122243
  total_trades: 21
  win_rate: 61.904761904761905
risk_management:
  stop_loss_atr_multiplier: 2.0
  take_profit_atr_multiplier: 3.0
rsi:
  length: 14
  overbought: 70
  oversold: 30
support_resistance:
  resistance_period: 20
  support_period: 20
