- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.9513903154155363
  final_capital: 10885.11835077498
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.925329219077278
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 885.1183507749788
  sharpe_ratio: 0.03895567065059972
  total_trades: 8
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.9513903154155363
  final_capital: 10885.11835077498
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.925329219077278
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 885.1183507749788
  sharpe_ratio: 0.03895567065059972
  total_trades: 8
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.9513903154155363
  final_capital: 10885.11835077498
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.925329219077278
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 885.1183507749788
  sharpe_ratio: 0.03895567065059972
  total_trades: 8
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.9513903154155363
  final_capital: 10885.11835077498
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.925329219077278
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 885.1183507749788
  sharpe_ratio: 0.03895567065059972
  total_trades: 8
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.9513903154155363
  final_capital: 10885.11835077498
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.925329219077278
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 885.1183507749788
  sharpe_ratio: 0.03895567065059972
  total_trades: 8
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.9513903154155363
  final_capital: 10885.11835077498
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.925329219077278
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 885.1183507749788
  sharpe_ratio: 0.03895567065059972
  total_trades: 8
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.9513903154155363
  final_capital: 10885.11835077498
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.925329219077278
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 885.1183507749788
  sharpe_ratio: 0.03895567065059972
  total_trades: 8
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.9513903154155363
  final_capital: 10885.11835077498
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.925329219077278
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 885.1183507749788
  sharpe_ratio: 0.03895567065059972
  total_trades: 8
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.9513903154155363
  final_capital: 10885.11835077498
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.925329219077278
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 885.1183507749788
  sharpe_ratio: 0.03895567065059972
  total_trades: 8
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.9152446084236727
  final_capital: 10873.978715356505
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 2.925329219077278
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 873.9787153565044
  sharpe_ratio: 0.034493061866172715
  total_trades: 8
  win_rate: 75.0
