- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.4316663052687204
  final_capital: 10851.27308441927
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 1.564470119916042
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 851.2730844192706
  sharpe_ratio: 0.09059657879311783
  total_trades: 6
  win_rate: 83.33333333333334
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.4316663052687204
  final_capital: 10851.27308441927
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 1.564470119916042
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 851.2730844192706
  sharpe_ratio: 0.09059657879311783
  total_trades: 6
  win_rate: 83.33333333333334
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.4316663052687204
  final_capital: 10851.27308441927
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 1.564470119916042
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 851.2730844192706
  sharpe_ratio: 0.09059657879311783
  total_trades: 6
  win_rate: 83.33333333333334
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.4316663052687204
  final_capital: 10851.27308441927
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 1.564470119916042
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 851.2730844192706
  sharpe_ratio: 0.09059657879311783
  total_trades: 6
  win_rate: 83.33333333333334
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.4316663052687204
  final_capital: 10851.27308441927
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 1.564470119916042
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 851.2730844192706
  sharpe_ratio: 0.09059657879311783
  total_trades: 6
  win_rate: 83.33333333333334
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.4316663052687204
  final_capital: 10851.27308441927
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 1.564470119916042
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 851.2730844192706
  sharpe_ratio: 0.09059657879311783
  total_trades: 6
  win_rate: 83.33333333333334
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.2970155367614717
  final_capital: 11163.194883958316
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 1.5631168463739884
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 2.5
    rsi:
      length: 20
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1163.1948839583165
  sharpe_ratio: -0.020612262870237284
  total_trades: 9
  win_rate: 88.88888888888889
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.2970155367614717
  final_capital: 11163.194883958316
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 1.5631168463739884
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 2.5
    rsi:
      length: 20
      overbought: 70
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1163.1948839583165
  sharpe_ratio: -0.020612262870237284
  total_trades: 9
  win_rate: 88.88888888888889
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.2970155367614717
  final_capital: 11163.194883958316
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 1.5631168463739884
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 30
      std: 1.8
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 2.5
    rsi:
      length: 20
      overbought: 75
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 1163.1948839583165
  sharpe_ratio: -0.020612262870237284
  total_trades: 9
  win_rate: 88.88888888888889
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.4349734968591052
  final_capital: 10852.464474584796
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 1.5535330546468926
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 25
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 852.4644745847959
  sharpe_ratio: -0.06459390195259397
  total_trades: 7
  win_rate: 71.42857142857143
