- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 9.220581667384241
  final_capital: 15010.4822250958
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.450989396416454
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 5010.4822250958005
  sharpe_ratio: 0.2916091104081171
  total_trades: 16
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 9.220581667384241
  final_capital: 15010.4822250958
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.450989396416454
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 5010.4822250958005
  sharpe_ratio: 0.2916091104081171
  total_trades: 16
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 9.220581667384241
  final_capital: 15010.4822250958
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.450989396416454
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 5010.4822250958005
  sharpe_ratio: 0.2916091104081171
  total_trades: 16
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 9.409824349432983
  final_capital: 15130.626014282872
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 5.912056006067217
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 5130.626014282873
  sharpe_ratio: 0.28044832263540403
  total_trades: 17
  win_rate: 70.58823529411765
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 9.409824349432983
  final_capital: 15130.626014282872
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 5.912056006067217
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 5130.626014282873
  sharpe_ratio: 0.28044832263540403
  total_trades: 17
  win_rate: 70.58823529411765
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 9.409824349432983
  final_capital: 15130.626014282872
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 5.912056006067217
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 5130.626014282873
  sharpe_ratio: 0.28044832263540403
  total_trades: 17
  win_rate: 70.58823529411765
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 9.10206561183815
  final_capital: 14932.059785832189
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.50667351691668
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 30
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 4932.05978583219
  sharpe_ratio: 0.2790112845467585
  total_trades: 16
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 9.10206561183815
  final_capital: 14932.059785832189
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.50667351691668
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 30
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 4932.05978583219
  sharpe_ratio: 0.2790112845467585
  total_trades: 16
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 9.10206561183815
  final_capital: 14932.059785832189
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.50667351691668
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 30
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 4932.05978583219
  sharpe_ratio: 0.2790112845467585
  total_trades: 16
  win_rate: 75.0
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 8.824769383319664
  final_capital: 14605.222145137395
  initial_capital: 10000.0
  max_capital_used: 10000.0
  max_concurrent_trades: 1
  max_drawdown: 6.623107010105852
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 30
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 4605.222145137395
  sharpe_ratio: 0.26781814671381365
  total_trades: 15
  win_rate: 73.33333333333333
