- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.1447533317064957
  final_capital: 1140711.087862863
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 3.7794591828367774
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 140711.08786286306
  sharpe_ratio: 0.13828642416156658
  total_trades: 14
  win_rate: 71.42857142857143
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.1447533317064957
  final_capital: 1140711.087862863
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 3.7794591828367774
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 70
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 140711.08786286306
  sharpe_ratio: 0.13828642416156658
  total_trades: 14
  win_rate: 71.42857142857143
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.1447533317064957
  final_capital: 1140711.087862863
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 3.7794591828367774
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 75
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 140711.08786286306
  sharpe_ratio: 0.13828642416156658
  total_trades: 14
  win_rate: 71.42857142857143
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.1447533317064957
  final_capital: 1140711.087862863
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 3.7794591828367774
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 140711.08786286306
  sharpe_ratio: 0.13828642416156658
  total_trades: 14
  win_rate: 71.42857142857143
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.1447533317064957
  final_capital: 1140711.087862863
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 3.7794591828367774
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 70
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 140711.08786286306
  sharpe_ratio: 0.13828642416156658
  total_trades: 14
  win_rate: 71.42857142857143
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.1447533317064957
  final_capital: 1140711.087862863
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 3.7794591828367774
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 75
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 140711.08786286306
  sharpe_ratio: 0.13828642416156658
  total_trades: 14
  win_rate: 71.42857142857143
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.1447533317064957
  final_capital: 1140711.087862863
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 3.7794591828367774
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 140711.08786286306
  sharpe_ratio: 0.13828642416156658
  total_trades: 14
  win_rate: 71.42857142857143
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.1447533317064957
  final_capital: 1140711.087862863
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 3.7794591828367774
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 70
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 140711.08786286306
  sharpe_ratio: 0.13828642416156658
  total_trades: 14
  win_rate: 71.42857142857143
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.1447533317064957
  final_capital: 1140711.087862863
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 3.7794591828367774
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.0
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 14
      overbought: 75
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 140711.08786286306
  sharpe_ratio: 0.13828642416156658
  total_trades: 14
  win_rate: 71.42857142857143
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.0255775286356146
  final_capital: 1135117.6103836407
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.6199747135692952
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 20
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 30
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 135117.61038364083
  sharpe_ratio: 0.11098380166321557
  total_trades: 14
  win_rate: 71.42857142857143
