- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.6869147766771295
  final_capital: 1118930.8310438015
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.254512675124722
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 40
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 118930.83104380142
  sharpe_ratio: 0.09164270884743392
  total_trades: 13
  win_rate: 76.92307692307693
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.6869147766771295
  final_capital: 1118930.8310438015
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.254512675124722
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 40
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 118930.83104380142
  sharpe_ratio: 0.09164270884743392
  total_trades: 13
  win_rate: 76.92307692307693
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.6869147766771295
  final_capital: 1118930.8310438015
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.254512675124722
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 40
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 118930.83104380142
  sharpe_ratio: 0.09164270884743392
  total_trades: 13
  win_rate: 76.92307692307693
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.6859654962569923
  final_capital: 1118805.8005766058
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.365260263928503
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 118805.8005766058
  sharpe_ratio: 0.08794252376258063
  total_trades: 13
  win_rate: 76.92307692307693
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.6859654962569923
  final_capital: 1118805.8005766058
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.365260263928503
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 118805.8005766058
  sharpe_ratio: 0.08794252376258063
  total_trades: 13
  win_rate: 76.92307692307693
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.6859654962569923
  final_capital: 1118805.8005766058
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.365260263928503
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.0
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 118805.8005766058
  sharpe_ratio: 0.08794252376258063
  total_trades: 13
  win_rate: 76.92307692307693
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.6859654962569923
  final_capital: 1118805.8005766058
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.365260263928503
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 118805.8005766058
  sharpe_ratio: 0.08794252376258063
  total_trades: 13
  win_rate: 76.92307692307693
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.6859654962569923
  final_capital: 1118805.8005766058
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.365260263928503
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 118805.8005766058
  sharpe_ratio: 0.08794252376258063
  total_trades: 13
  win_rate: 76.92307692307693
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.6859654962569923
  final_capital: 1118805.8005766058
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.365260263928503
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.0
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 118805.8005766058
  sharpe_ratio: 0.08794252376258063
  total_trades: 13
  win_rate: 76.92307692307693
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 2.385813444428786
  final_capital: 1105020.0307133275
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 2.3944089626721627
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.0
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 2.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 105020.03071332752
  sharpe_ratio: 0.05645283265776839
  total_trades: 12
  win_rate: 75.0
