- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.7295576226719085
  final_capital: 1036541.9182750023
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.6873967561273133
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 36541.91827500229
  sharpe_ratio: 0.30782072024370283
  total_trades: 3
  win_rate: 66.66666666666666
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.7295576226719085
  final_capital: 1036541.9182750023
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.6873967561273133
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 36541.91827500229
  sharpe_ratio: 0.30782072024370283
  total_trades: 3
  win_rate: 66.66666666666666
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.7295576226719085
  final_capital: 1036541.9182750023
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.6873967561273133
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 36541.91827500229
  sharpe_ratio: 0.30782072024370283
  total_trades: 3
  win_rate: 66.66666666666666
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.7295576226719085
  final_capital: 1036541.9182750023
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.6873967561273133
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 36541.91827500229
  sharpe_ratio: 0.30782072024370283
  total_trades: 3
  win_rate: 66.66666666666666
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.7295576226719085
  final_capital: 1036541.9182750023
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.6873967561273133
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 36541.91827500229
  sharpe_ratio: 0.30782072024370283
  total_trades: 3
  win_rate: 66.66666666666666
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.7295576226719085
  final_capital: 1036541.9182750023
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.6873967561273133
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 15
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 36541.91827500229
  sharpe_ratio: 0.30782072024370283
  total_trades: 3
  win_rate: 66.66666666666666
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.7295576226719085
  final_capital: 1036541.9182750023
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.6873967561273133
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 36541.91827500229
  sharpe_ratio: 0.30782072024370283
  total_trades: 3
  win_rate: 66.66666666666666
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.7295576226719085
  final_capital: 1036541.9182750023
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.6873967561273133
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 70
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 36541.91827500229
  sharpe_ratio: 0.30782072024370283
  total_trades: 3
  win_rate: 66.66666666666666
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.7295576226719085
  final_capital: 1036541.9182750023
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.6873967561273133
  parameters:
    atr:
      window: 10
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 20
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 75
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 36541.91827500229
  sharpe_ratio: 0.30782072024370283
  total_trades: 3
  win_rate: 66.66666666666666
- additional_capital_required: 0.0
  avg_capital_utilization: 0.0
  cagr: 3.6028729769838064
  final_capital: 1035301.105107594
  initial_capital: 1000000.0
  max_capital_used: 1000000.0
  max_concurrent_trades: 1
  max_drawdown: 0.715738086434026
  parameters:
    atr:
      window: 14
    bollinger_bands:
      length: 40
      std: 2.2
    ema:
      period: 10
    macd:
      fast_period: 8
      signal_period: 7
      slow_period: 21
    risk_management:
      stop_loss_atr_multiplier: 1.5
      take_profit_atr_multiplier: 3.0
    rsi:
      length: 10
      overbought: 65
      oversold: 35
    support_resistance:
      resistance_period: 10
      support_period: 10
  realized_pnl: 35301.1051075941
  sharpe_ratio: 0.279169754059267
  total_trades: 3
  win_rate: 66.66666666666666
